-- create business event outbox table --
create table ACT_RU_BUS_EVT_OBX (
    ID_               bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CREATED_DATE_     timestamp NOT NULL,
    BUSINESS_EVENT_   clob NOT NULL,
    EVENT_TYPE_       varchar(255),
    PROC_INST_ID_     varchar(64),
    ROOT_PROC_INST_ID_ varchar(64),
    PROC_DEF_KEY_     varchar(255),
    TASK_ID_          varchar(64),
    PROCESSED_        boolean NOT NULL DEFAULT false,
    PROCESSED_DATE_   timestamp,
    primary key (ID_)
);
create index ACT_IDX_BEO_PROC_INST on ACT_RU_BUS_EVT_OBX(PROC_INST_ID_);
create index ACT_IDX_BEO_UNPROCESSED on ACT_RU_BUS_EVT_OBX(PROCESSED_, ID_);
