-- create business event outbox table --
create table ACT_RU_BUS_EVT_OBX (
    ID_               bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    CREATED_DATE_     timestamp not null,
    BUSINESS_EVENT_   clob not null,
    EVENT_TYPE_       varchar(255),
    PROC_INST_ID_     varchar(64),
    ROOT_PROC_INST_ID_ varchar(64),
    PROC_DEF_KEY_     varchar(255),
    TASK_ID_          varchar(64),
    PROCESSED_        smallint not null default 0 check(PROCESSED_ in (1,0)),
    PROCESSED_DATE_   timestamp,
    primary key (ID_)
);
create index ACT_IDX_BEO_PROC_INST on ACT_RU_BUS_EVT_OBX(PROC_INST_ID_);
create index ACT_IDX_BEO_UNPROCESSED on ACT_RU_BUS_EVT_OBX(ID_) WHERE PROCESSED_ = 0;
