insert into ACT_GE_SCHEMA_LOG
values ('1400', CURRENT_TIMESTAMP, '1.3.0');
-- create business event outbox table --
create table ACT_RU_BUS_EVT_OBX (
    ID_               NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    CREATED_DATE_     TIMESTAMP(6) NOT NULL,
    BUSINESS_EVENT_   CLOB NOT NULL,
    EVENT_TYPE_       NVARCHAR2(255),
    PROC_INST_ID_     NVARCHAR2(64),
    ROOT_PROC_INST_ID_ NVARCHAR2(64),
    PROC_DEF_KEY_     NVARCHAR2(255),
    TASK_ID_          NVARCHAR2(64),
    PROCESSED_        NUMBER(1,0) NOT NULL DEFAULT 0 CHECK (PROCESSED_ IN (1,0)),
    PROCESSED_DATE_   TIMESTAMP(6),
    primary key (ID_)
);
create index ACT_IDX_BEO_PROC_INST on ACT_RU_BUS_EVT_OBX(PROC_INST_ID_);
create index ACT_IDX_BEO_UNPROCESSED on ACT_RU_BUS_EVT_OBX(PROCESSED_, ID_);

-- script guard violation log --
create table ACT_RU_SCRIPT_VIOLATION (
                                         ID_               NVARCHAR2(64) not null,
                                         TIMESTAMP_        TIMESTAMP(6) not null,
                                         PROC_DEF_KEY_     NVARCHAR2(255),
                                         ACTIVITY_ID_      NVARCHAR2(255),
                                         LANGUAGE_         NVARCHAR2(64),
                                         SOURCE_TYPE_      NVARCHAR2(64),
                                         ORIGIN_           NVARCHAR2(64),
                                         RULE_CODE_        NVARCHAR2(255),
                                         REASON_           NVARCHAR2(1000),
                                         primary key (ID_)
);
