name: build

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: self-hosted
    outputs:
      skip_build: ${{ steps.verify.outputs.skip_build }}
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get list of changed files
        id: verify
        run: |
          echo "Checking for relevant file changes..."
          
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
          
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          IGNORED_PATTERNS=(
            ".github/scripts/"
            ".github/workflows/"     
            ".github/jreleaser/changelog.tpl"
            ".md"
            "distro/"
            "settings/"
            ".gitignore"
            "LICENSE"
            "NOTICE"
          )
          
          RELEVANT_FILES=()
          
          for FILE in $CHANGED_FILES; do
            SKIP=false
          
            # exception for build.yml
            if [[ "$FILE" == ".github/workflows/build.yml" ]]; then
              RELEVANT_FILES+=("$FILE")
              continue
            fi
          
            for PATTERN in "${IGNORED_PATTERNS[@]}"; do
              if [[ "$FILE" == "$PATTERN"* ]] || [[ "$FILE" == *"$PATTERN" ]]; then
                SKIP=true
                break
              fi
            done
          
            if [ "$SKIP" = false ]; then
              RELEVANT_FILES+=("$FILE")
            fi
          done
          
          echo "Relevant files:"
          printf "%s\n" "${RELEVANT_FILES[@]}"
          
          if [ ${#RELEVANT_FILES[@]} -eq 0 ]; then
            echo "No relevant files changed — skipping build."
            echo "skip_build=true" >> $GITHUB_OUTPUT
          else
            echo "Relevant files found — proceeding with build."
            echo "skip_build=false" >> $GITHUB_OUTPUT
          fi
      - name: Stop early if no relevant files
        if: steps.verify.outputs.skip_build == 'true'
        run: |
          echo "Nothing to do. Exiting early."
          exit 0

  build:
    name: Build
    needs: check
    if: needs.check.outputs.skip_build == 'false'
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          overwrite-settings: false

      - name: Create custom settings.xml
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${GITHUB_ACTOR}</username>
                <password>${GITHUB_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Maven Build
        id: maven-build
        shell: bash
        run: |
          ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=EximeeBPMS_eximeebpms
          ./mvnw --non-recursive org.jacoco:jacoco-maven-plugin:report-aggregate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: ${{ github.workspace }}/**/target/surefire-reports/*.xml
          require_passed_tests: true

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: ${{ github.workspace }}/**/target/surefire-reports/**
          retention-days: 30
