name: Integration Tests

on:
  schedule:
    - cron: '0 4 * * *' 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'main'
        type: string
      java_version:
        description: 'Java version to use'
        type: choice
        required: true
        default: '["17"]'
        options:
          - '["17"]'
          - '["21"]'
          - '["17", "21"]'
      testsuite:
        description: 'Integration test suite to run'
        type: choice
        required: true
        default: '["engine"]'
        options:
          - '["engine"]'
      container:
        description: 'Container to use for integration tests'
        type: choice
        required: true
        default: '["tomcat"]'
        options:
          - '["tomcat"]'
      database:
        description: 'Database to use for integration tests'
        type: choice
        required: true
        default: '["h2", "postgresql"]'
        options:
          - '["h2"]'
          - '["postgresql"]'
          - '["h2", "postgresql"]'

permissions:
  contents: read
  checks: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Integration Tests
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        java: ${{ fromJson(github.event.inputs.java_version || '["17"]') }}
        testsuite: ${{ fromJson(github.event.inputs.testsuite || '["engine", "webapps"]') }}
        distro: ${{ fromJson(github.event.inputs.container || '["tomcat", "wildfly"]') }}
        database: ${{ fromJson(github.event.inputs.database || '["h2", "postgresql"]') }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch || 'main' }}
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          overwrite-settings: false

      - name: Maven Build
        id: maven-build
        shell: bash
        run: |
          .github/scripts/run-integration-tests.sh --testsuite=${{ matrix.testsuite }} --distro=${{ matrix.distro }} --db=${{ matrix.database }} --no-test

      - name: Execute Integration Tests
        id: maven-integration-tests
        shell: bash
        run: |
          if [[ "${{ matrix.distro }}" == "wildfly" && "${{ matrix.database }}" == "postgresql" && "${{ github.event_name }}" == "schedule" ]]; then
            echo "Warning: Skipping build for distro 'wildfly' with database 'postgresql' due."
            exit 0
          fi
          .github/scripts/run-integration-tests.sh --testsuite=${{ matrix.testsuite }} --distro=${{ matrix.distro }} --db=${{ matrix.database }} --no-build
#      - name: Publish Test Report
#        if: always()
#        uses: mikepenz/action-junit-report@v4
#        with:
#          report_paths: ${{ github.workspace }}/**/target/*-reports/*.xml
#          require_passed_tests: true
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ matrix.testsuite }}-${{ matrix.distro }}-${{ matrix.database }}
          path: |
            ${{ github.workspace }}/**/target/surefire-reports/**
            ${{ github.workspace }}/**/target/failsafe-reports/**
            ${{ github.workspace }}/qa/**/target/**/logs/**
            ${{ github.workspace }}/**/target/cargo.log
          retention-days: 30
