name: Release

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'The branch to release from'
        required: true
        default: 'main'
      release_version:
        description: 'Release version to set'
        required: true
        default: '0.9.0'
      development_version:
        description: 'The next development version to set (without -SNAPSHOT suffix)'
        required: true
        default: '0.10.0'
      # dry_run:
      #   description: 'Dry-Run: Skips remote operations when true'
      #   type: boolean
      #   required: true
      #   default: true

permissions:
  contents: write
  packages: write
  actions: write
  checks: write
  deployments: write
  issues: write
  discussions: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
        
jobs:

   release_build:
      name: Release Build
      runs-on: self-hosted
      steps:
        - name: Set the token based on actor
          id: set-token
          run: |
            echo "Actor is: ${{ github.actor }}"
            
            case "${{ github.actor }}" in
              "dkubiak")
                echo "Using PAT for dkubiak"
                echo "PAT=${{ secrets.PAT_DKUBIAK }}" >> $GITHUB_ENV
                ;;
            esac
        - name: Check out the code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            ref: ${{github.event.inputs.release_branch}}
        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Create custom settings.xml
          run: |
            mkdir -p ~/.m2
            cat <<EOF > ~/.m2/settings.xml
            <settings>
              <servers>
                <server>
                  <id>github-eximeebpms-release-parent</id>
                  <username>${GITHUB_ACTOR}</username>
                  <password>${PAT}</password>
                </server>
              </servers>
            </settings>
            EOF
          env:
            GITHUB_ACTOR: ${{ github.actor }}
  
        - name: Release prepare with Maven
          run: |
            ./mvnw release:prepare release:perform -B \
              -DignoreSnapshots=true -DremoteTagging=false \
              -DreleaseVersion=${{ github.event.inputs.release_version }} \
              -DdevelopmentVersion=${{ github.event.inputs.development_version }}-SNAPSHOT \
              -Darguments="-DskipTests"
              
        - name: Create GitHub Release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: v${{ github.event.inputs.release_version }}
            name: Release v${{ github.event.inputs.release_version }}
            draft: false
            prerelease: false
            description: |
              Release generated on ${{ github.event.head_commit.timestamp }}
              with commit message: ${{ github.event.head_commit.message }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
