name: Release

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to release'
        required: true
      development_version:
        description: 'Next snapshot version'
        required: true

jobs:


#  Invoking snapshot release to provide the necessary snapshots for testing in CustomJacksonDateFormatTest
  call-snapshot-release:
    permissions:
      contents: write
      packages: write

    uses: ./.github/workflows/snapshots-release.yml

    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      CPP_USERNAME: ${{ secrets.CPP_USERNAME }}
      CPP_PASSWORD: ${{ secrets.CPP_PASSWORD }}
      SECRET_PAT_USER: ${{ secrets.SECRET_PAT_userlogin }}
