name: Slack Notifications

permissions:
  issues: read
  pull-requests: read
  discussions: read
  actions: read

on:
  workflow_dispatch:
  fork:
  discussion:
  discussion_comment:
  issues:
  issue_comment:
  pull_request_review_comment:
  pull_request_review:
  pull_request:
  watch:
  release:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["build", "Integration Tests", "Release", "Snapshot release on main", "Snapshot release", "Renovate auto-merge"]
    types:
      - completed

jobs:
  notify_slack:
    runs-on: self-hosted
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Set Event Message
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_HTML_URL: ${{ github.event.html_url || '-' }}
          GITHUB_EVENT_ACTION: ${{ github.event.action }}
          SENDER_LOGIN: ${{ github.event.sender.login }}
          REF_NAME: ${{ github.ref_name }}
          ACTOR: ${{ github.actor }}
          COMPARE_URL: ${{ github.event.compare }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
          RELEASE_HTML_URL: ${{ github.event.release.html_url }}
          WORKFLOW_RUN_NAME: ${{ github.event.workflow_run.name }}
          WORKFLOW_RUN_HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
          WORKFLOW_RUN_HTML_URL: ${{ github.event.workflow_run.html_url }}
          DISCUSSION_HTML_URL: ${{ github.event.discussion.html_url }}
          COMMENT_HTML_URL: ${{ github.event.comment.html_url }}
          ISSUE_HTML_URL: ${{ github.event.issue.html_url }}
          PR_HTML_URL: ${{ github.event.pull_request.html_url }}
          PR_MERGED: ${{ github.event.pull_request.merged }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          REVIEW_HTML_URL: ${{ github.event.review.html_url }}
        run: |
          set -u

          msg="🔔 New event of type *$GITHUB_EVENT_NAME* detected!"
          details="Details: $GITHUB_EVENT_HTML_URL"

          case "$GITHUB_EVENT_NAME" in
            fork)     msg="🍴 Repository was forked!";;
            watch)    msg="⭐ *<${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>* starred the repository!";;

            push)
              msg="📦 New commit pushed to *$REF_NAME* by <${{ github.server_url }}/$ACTOR|$ACTOR>!"
              details="<$COMPARE_URL|View changes>"
            ;;

            release)
              case "$GITHUB_EVENT_ACTION" in
                published)
                  msg="🚀 Release *$RELEASE_TAG_NAME* published by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$RELEASE_HTML_URL"
                ;;

                prereleased)
                  msg="🔖 Pre-release *$RELEASE_TAG_NAME* published by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$RELEASE_HTML_URL"
                ;;

                created)
                  msg="🏷️ Release *$RELEASE_TAG_NAME* created by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$RELEASE_HTML_URL"
                ;;

                edited)
                  msg="✏️ Release *$RELEASE_TAG_NAME* was edited by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$RELEASE_HTML_URL"
                ;;

                deleted)
                  msg="🗑️ Release *$RELEASE_TAG_NAME* was deleted by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$RELEASE_HTML_URL"
                ;;
              esac
            ;;

            workflow_run)
              msg="❌ Workflow *$WORKFLOW_RUN_NAME* failed on branch *$WORKFLOW_RUN_HEAD_BRANCH*!"
              details="<$WORKFLOW_RUN_HTML_URL|View run>"
            ;;

            discussion)
              case "$GITHUB_EVENT_ACTION" in
                created)
                  msg="💬 New Discussion Created by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$DISCUSSION_HTML_URL"
                ;;

                edited)
                  msg="✏️ Discussion was modified by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$DISCUSSION_HTML_URL"
                ;;

                closed)
                  msg="✅ Discussion Closed by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$DISCUSSION_HTML_URL"
                ;;

                reopened)
                  msg="🔄 Discussion Reopened by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$DISCUSSION_HTML_URL"
                ;;

                *)
                  msg="💬 Discussion Event *$GITHUB_EVENT_ACTION* by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$DISCUSSION_HTML_URL"
                ;;
              esac
            ;;

            discussion_comment)
              case "$GITHUB_EVENT_ACTION" in
                created)
                  msg="💬 New comment was added to the discussion by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>."
                  details="Discussion $DISCUSSION_HTML_URL, comment $COMMENT_HTML_URL"
                ;;

                edited)
                  msg="️️✏️ An existing comment in the discussion was edited by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>."
                  details="Discussion $DISCUSSION_HTML_URL, comment $COMMENT_HTML_URL"
                ;;

                deleted)
                  msg="🗑 A comment was removed from the discussion by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>"
                  details="Discussion $DISCUSSION_HTML_URL"
                ;;
              esac
            ;;

            issues)
              case "$GITHUB_EVENT_ACTION" in
                opened)
                  msg="🐛 New Issue Created by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$ISSUE_HTML_URL"
                ;;

                reopened)
                  msg="🔄 Issue Reopened by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$ISSUE_HTML_URL"
                ;;

                closed)
                  msg="✅ Issue Closed by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$ISSUE_HTML_URL"
                ;;

                *)
                  msg="🐛 Issue Event *$GITHUB_EVENT_ACTION* by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$ISSUE_HTML_URL"
                ;;
              esac
            ;;

            issue_comment)
              case "$GITHUB_EVENT_ACTION" in
                created)
                  msg="💬 New Issue Comment added by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$ISSUE_HTML_URL"
                ;;

                edited)
                  msg="✏️ Issue Comment modified by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$ISSUE_HTML_URL"
                ;;

                deleted)
                  msg="🗑️ Issue Comment deleted by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$ISSUE_HTML_URL"
                ;;
              esac
            ;;


            pull_request)
              case "$GITHUB_EVENT_ACTION" in
                opened)
                  msg="🔀 New Pull Request was created by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$PR_HTML_URL"
                ;;

                reopened)
                  msg="♻️ Pull Request Reopened by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$PR_HTML_URL"
                ;;

                edited)
                  msg="✏️ Pull Request Modified by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="$PR_HTML_URL"
                ;;

                closed)
                  if [ "$PR_MERGED" = "true" ]; then
                    msg="🎉 Pull Request Merged by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  else
                    msg="❌ Pull Request Closed by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  fi
                  details="$PR_HTML_URL"
                ;;

                *)
                  msg="🔀 Pull Request Event: *$GITHUB_EVENT_ACTION*!"
                  details="$PR_HTML_URL"
                ;;
              esac
            ;;

            pull_request_review)
              case "$GITHUB_EVENT_ACTION" in
                submitted)
                  msg="💬️ A review was added to the Pull Request by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="PR: <$PR_HTML_URL|$PR_TITLE>, <$REVIEW_HTML_URL|Review>"
                ;;

                edited)
                  msg="✏️️ Pull Request review was modified by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="PR: <$PR_HTML_URL|$PR_TITLE>, <$REVIEW_HTML_URL|Review>"
                ;;

                dismissed)
                  msg="🚫 Pull Request review was dismissed by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="PR: <$PR_HTML_URL|$PR_TITLE>"
                ;;
              esac
            ;;

            pull_request_review_comment)
              case "$GITHUB_EVENT_ACTION" in
                created)
                  msg="💬️ A new comment was added to the Pull Request by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN>!"
                  details="PR: <$PR_HTML_URL|$PR_TITLE>, <$COMMENT_HTML_URL|Comment>"
                ;;

                edited)
                  msg="✏️️ A comment has been modified by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN> in the Pull Request!"
                  details="PR: <$PR_HTML_URL|$PR_TITLE>, <$COMMENT_HTML_URL|Comment>"
                ;;

                deleted)
                  msg="🗑️ A comment was deleted by <${{ github.server_url }}/$SENDER_LOGIN|$SENDER_LOGIN> in the Pull Request!"
                  details="PR: <$PR_HTML_URL|$PR_TITLE>"
                ;;
              esac
            ;;
          esac

          echo "EVENT_MSG=$msg" >> $GITHUB_ENV
          echo "DETAILS=$details" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🔔 *New event* ${{ github.event.created_at }} 🔔"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.EVENT_MSG }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Repository:* <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}> _(OSS)_"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.DETAILS }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
